#!/bin/sh
# Make the xemu container's per-instance CA trusted by Firefox so the kiosk loads
# https://localhost:<XemuHTTPS> (xemu's noVNC view, served by nginx with our
# SAN-pinned leaf) without the "Potential Security Risk Ahead" interstitial. The
# CA is generated by internal/podman/cert.go:generateXemuCerts and bind-mounted
# read-only at /xemu-cert.
#
# PRIMARY trust path is host-side: the podman provisioner pre-seeds this
# instance's Firefox profile NSS DB (/config/profile/cert9.db) with the CA at
# create time, using the host's certutil (internal/podman/browser_cert.go). That
# is version-stable and verifiable off-box, and does NOT depend on this image
# shipping nss-tools.
#
# This script is the DURABLE BELT for that: a Mozilla enterprise policy
# (policies.json) that installs the CA into Firefox's trust store. It needs no
# extra packages and is independent of the per-profile NSS DB, so it covers the
# host-certutil-unavailable case and the "profile reset via DELETE /files then
# restart" recovery path (where the pre-seeded DB was wiped). It references the
# bind-mounted CA by path, so it survives cert rotation.
set -eu

CERT=/xemu-cert/ca.pem

if [ ! -f "$CERT" ]; then
    echo "[trust-xemu-cert] $CERT not found, skipping"
    exit 0
fi

# Drop a policies.json into every well-known Firefox policy dir. Firefox checks
# these on startup; an extra file in a non-existent install path is harmless. The
# Alpine `firefox` package (jlesage/firefox) installs to /usr/lib/firefox, so
# /usr/lib/firefox/distribution/policies.json is the one that binds here;
# /etc/firefox/policies is the documented Linux system location. Inline JSON keeps
# the script self-contained. `Install` installs the CA file directly (the useful
# key on Linux; ImportEnterpriseRoots only reads the OS store and is a no-op here,
# left in as documentation of intent).
POLICY_JSON='{"policies":{"Certificates":{"ImportEnterpriseRoots":true,"Install":["/xemu-cert/ca.pem"]}}}'

for dir in \
    /etc/firefox/policies \
    /usr/lib/firefox/distribution \
    /usr/lib/firefox-esr/distribution \
    /opt/firefox/distribution
do
    if mkdir -p "$dir" 2>/dev/null; then
        if printf '%s\n' "$POLICY_JSON" > "$dir/policies.json"; then
            echo "[trust-xemu-cert] wrote $dir/policies.json"
        fi
    fi
done
