<script lang="ts">
	import {
		AlertTriangleIcon,
		CheckCircle2Icon,
		CopyIcon,
		DownloadIcon,
		FileDownIcon,
		HardDriveIcon,
		LoaderIcon
	} from '@lucide/svelte';
	import { lanBuild, lanDownload, lanDownloadURL, LanSavesError } from '$lib/utils/lansaves';
	import { toaster } from '$lib/stores/toaster';
	import type { BuildRequest, BuildResponse, DownloadFormat } from '$lib/types/lansaves';

	let { req }: { req: BuildRequest } = $props();

	let preview = $state<BuildResponse | null>(null);
	let error = $state<string | null>(null);
	let loading = $state(false);
	let downloading = $state(false);
	let freeBytes = $state<number | undefined>(undefined);

	// Debounced live preview: re-validate whenever the request changes.
	$effect(() => {
		const snapshot = JSON.stringify(req);
		if (!req.name?.trim()) {
			preview = null;
			error = 'Enter a name to generate a file.';
			return;
		}
		let cancelled = false;
		loading = true;
		const t = setTimeout(async () => {
			try {
				const r = await lanBuild(JSON.parse(snapshot));
				if (!cancelled) {
					preview = r;
					error = null;
				}
			} catch (e) {
				if (!cancelled) {
					preview = null;
					error = e instanceof Error ? e.message : String(e);
				}
			} finally {
				if (!cancelled) loading = false;
			}
		}, 200);
		return () => {
			cancelled = true;
			clearTimeout(t);
		};
	});

	const fits = $derived(
		preview && freeBytes !== undefined && Number.isFinite(freeBytes)
			? preview.footprint_bytes <= freeBytes
			: null
	);

	const lanURL = $derived(lanDownloadURL(req, 'tar', freeBytes));

	async function download(format: DownloadFormat) {
		downloading = true;
		try {
			const name = await lanDownload(req, format, freeBytes);
			toaster.success({ title: 'Downloaded', description: name });
		} catch (e) {
			if (e instanceof LanSavesError && e.status === 507) {
				toaster.error({
					title: 'Insufficient storage',
					description:
						'The target does not have room for this save. Increase free space or lower the reported free bytes.'
				});
			} else {
				toaster.error({
					title: 'Download failed',
					description: e instanceof Error ? e.message : String(e)
				});
			}
		} finally {
			downloading = false;
		}
	}

	async function copyURL() {
		try {
			await navigator.clipboard.writeText(lanURL);
			toaster.success({ title: 'Copied', description: 'LAN download URL copied to clipboard' });
		} catch {
			toaster.error({ title: 'Copy failed', description: 'Clipboard unavailable' });
		}
	}

	function fmtBytes(n: number): string {
		if (n < 1024) return `${n} B`;
		if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KiB`;
		return `${(n / 1024 / 1024).toFixed(2)} MiB`;
	}

	function parsedEntries(p: Record<string, unknown> | undefined): [string, string][] {
		if (!p) return [];
		return Object.entries(p)
			.filter(([k, v]) => k !== 'digest' && (typeof v === 'string' || typeof v === 'number'))
			.map(([k, v]) => [k, String(v)]);
	}
</script>

<div class="flex flex-col gap-4">
	<header class="flex items-center gap-2">
		<HardDriveIcon class="size-5 text-primary-500" />
		<h3 class="h4">Generated save</h3>
		{#if loading}<LoaderIcon class="size-4 animate-spin text-surface-500" />{/if}
	</header>

	{#if error}
		<div class="card preset-tonal-error p-4 text-sm">{error}</div>
	{:else if preview}
		<!-- Where it goes -->
		<div class="space-y-1 card p-4 text-sm">
			<div class="flex justify-between gap-2">
				<span class="text-surface-600-400">Save directory</span>
				<span class="font-mono">{preview.dir_name}</span>
			</div>
			<div class="flex justify-between gap-2">
				<span class="text-surface-600-400">FATX path</span>
				<span class="font-mono text-xs break-all">E:\{preview.fatx_dir.replaceAll('/', '\\')}</span>
			</div>
		</div>

		<!-- Files -->
		<div class="card p-4">
			<h4 class="mb-2 text-xs font-semibold tracking-wide text-surface-600-400 uppercase">Files</h4>
			<table class="w-full text-sm">
				<thead class="text-surface-600-400">
					<tr class="text-left">
						<th class="pb-1 font-medium">Name</th>
						<th class="pb-1 font-medium">Size</th>
						<th class="pb-1 font-medium">SHA-1</th>
					</tr>
				</thead>
				<tbody class="font-mono">
					{#each preview.files as f (f.name)}
						<tr>
							<td class="py-0.5 pr-2">{f.name}</td>
							<td class="py-0.5 pr-2">{f.size}</td>
							<td class="py-0.5 text-xs text-surface-500">{f.sha1.slice(0, 12)}…</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>

		<!-- Round-trip: re-parsed fields -->
		<div class="card p-4">
			<h4 class="mb-2 text-xs font-semibold tracking-wide text-surface-600-400 uppercase">
				Decoded (re-parsed from generated bytes)
			</h4>
			<dl class="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
				{#each parsedEntries(preview.parsed) as [k, v] (k)}
					<dt class="text-surface-600-400">{k}</dt>
					<dd class="text-right font-mono">{v}</dd>
				{/each}
			</dl>
		</div>

		<!-- Footprint + disk check -->
		<div class="space-y-2 card p-4 text-sm">
			<div class="flex justify-between">
				<span class="text-surface-600-400"
					>On-disk footprint (FATX {fmtBytes(preview.fatx_cluster)} clusters)</span
				>
				<span class="font-mono">{fmtBytes(preview.footprint_bytes)}</span>
			</div>
			<label class="label">
				<span class="text-xs text-surface-600-400"
					>Target free bytes (optional — sent as the disk-space pre-flight)</span
				>
				<input
					type="number"
					class="input"
					placeholder="e.g. 33554432"
					bind:value={freeBytes}
					min="0"
				/>
			</label>
			{#if fits === true}
				<p class="flex items-center gap-1 text-success-600-400">
					<CheckCircle2Icon class="size-4" /> Fits — {fmtBytes(
						freeBytes! - preview.footprint_bytes
					)} to spare.
				</p>
			{:else if fits === false}
				<p class="flex items-center gap-1 text-error-500">
					<AlertTriangleIcon class="size-4" /> Does not fit — download will be refused (507).
				</p>
			{/if}
		</div>

		<!-- Digest + warnings -->
		<div
			class="card p-4 text-sm {preview.digest.edited
				? 'preset-tonal-warning'
				: 'preset-tonal-success'}"
		>
			<div class="flex items-center gap-2 font-medium">
				{#if preview.digest.edited}
					<AlertTriangleIcon class="size-4" /> Edited — 20-byte digest preserved from template
				{:else}
					<CheckCircle2Icon class="size-4" /> Unchanged clone — byte-identical to a real save
				{/if}
			</div>
			<p class="mt-1 text-xs opacity-90">{preview.digest.note}</p>
			{#if preview.warnings?.length}
				<ul class="mt-2 list-inside list-disc space-y-1 text-xs opacity-90">
					{#each preview.warnings as w (w)}<li>{w}</li>{/each}
				</ul>
			{/if}
		</div>

		<!-- Download controls -->
		<div class="flex flex-wrap gap-2">
			<button class="btn preset-filled" onclick={() => download('tar')} disabled={downloading}>
				{#if downloading}<LoaderIcon class="size-4 animate-spin" />{:else}<DownloadIcon
						class="size-4"
					/>{/if}
				<span>Download .tar</span>
			</button>
			<button class="btn preset-tonal" onclick={() => download('zip')} disabled={downloading}>
				<DownloadIcon class="size-4" /><span>.zip</span>
			</button>
			<button class="btn preset-tonal" onclick={() => download('payload')} disabled={downloading}>
				<FileDownIcon class="size-4" /><span>payload only</span>
			</button>
		</div>

		<!-- LAN client URL -->
		<div class="space-y-1 card p-4">
			<div class="flex items-center justify-between">
				<h4 class="text-xs font-semibold tracking-wide text-surface-600-400 uppercase">
					nxdk LAN client URL
				</h4>
				<button class="btn-icon preset-tonal btn-sm" title="Copy URL" onclick={copyURL}>
					<CopyIcon class="size-4" />
				</button>
			</div>
			<p class="font-mono text-xs break-all text-surface-700-300">{lanURL}</p>
			<p class="text-xs text-surface-500">
				GET this from the Xbox to download the generated save (with the disk-space pre-flight).
			</p>
		</div>
	{:else}
		<div class="card preset-tonal p-4 text-sm text-surface-600-400">No preview yet.</div>
	{/if}
</div>
