package haloce

// AllLowGVAs returns the low guest VAs this instance's offset set pre-translates
// at Instance.Init time — the versioned equivalent of the package-level
// AllLowGVAs constant list (same composition, values from the bound set).
func (o *Offsets) AllLowGVAs() []uint32 {
	return []uint32{
		o.AddrPlayerDatumArrayPtr,
		o.AddrPlayersGlobalsPtr,
		o.AddrTeamsPtr,
		o.AddrGameGlobalsPtr,
		o.AddrGlobalGameGlobalsPtr,
		o.AddrGameServerPtr,
		o.AddrGameClientPtr,
		o.AddrObjectHeaderDatumPtr,
		o.AddrGameTimeGlobalsPtr,
		o.AddrGlobalTagInstancesPtr,
		o.AddrGlobalScenarioPtr,
		o.AddrTagHeaderPtr,
		o.AddrGameEngineGlobalsPtr,
		o.AddrGameVariantGlobalPtr,
		o.AddrGameConnection,
		o.AddrIsTeamGame,
		o.AddrMainMenuActive,
		o.AddrGameCanScore,
		o.AddrGlobalStageName,
		o.AddrVariant,
		o.AddrScoreCTF,
		o.AddrScoreSlayer,
		o.AddrScoreOddball,
		o.AddrScoreKing,
		o.AddrScoreRace,
		o.AddrScoreLimitCTF,
		o.AddrScoreLimitSlayer,
		o.AddrScoreLimitOddball,
		o.RefAddrHudMessagesPtr,
		o.RefAddrPlayerControlPtr,
		o.RefAddrUpdateClientPlayerPtr,
		o.RefAddrFPWeaponPtr,
		o.RefAddrInputAbstractGlbls,
		o.RefAddrCTFFlag0Ptr,
		o.RefAddrCTFFlag1Ptr,
		o.RefAddrUpdateQueueCounterLo,
		o.RefAddrUpdateQueueCounterHi,
		o.RefAddrUpdateQueueAdjacent,
		o.RefAddrPerLocalUIGlobals,
		o.RefAddrInputAbstractInputState,
		o.RefAddrGamepadStateAlt,
		o.RefAddrGamepadState,
		o.RefAddrLookYawRate,
		o.RefAddrLookPitchRate,
		o.RefAddrObserverCameraBase,
		o.RefAddrNetworkGameClient,
		o.RefAddrNetworkGameServer,
		o.RefAddrFogParams,
		o.RefAddrGlobalVariant,
		o.RefAddrGlobalRandomSeed,
		o.RefAddrObjectTypeDefArray,
		o.RefAddrObjectDatumSize,
		o.RefAddrUnitDatumSize,
		o.RefAddrItemDatumSize,
		o.RefAddrObjectTypeDefRangeHi,
		o.RefAddrDefaultFramerate,
		o.RefAddrRefreshRate,
		o.RefAddrGameStateBasePtr,
		o.RefAddrTagCacheBasePtr,
		o.RefAddrTextureCacheBasePtr,
		o.RefAddrSoundCacheBasePtr,
		o.RefAddrGameStateSize,
		o.RefAddrTagCacheSize,
		o.RefAddrTextureCacheSize,
		o.RefAddrSoundCacheSize,
	}
}
